CREATE TABLE [dbo].[Flights] (
    [Date]                  DATE            NOT NULL,
    [AircraftID]            VARCHAR (100)   NULL,
    [From]                  VARCHAR (100)   NULL,
    [To]                    VARCHAR (100)   NULL,
    [Route]                 VARCHAR (100)   NULL,
    [TotalTime]             DECIMAL (18, 2) NULL,
    [PIC]                   DECIMAL (18, 2) NULL,
    [SIC]                   DECIMAL (18, 2) NULL,
    [Night]                 DECIMAL (18, 2) NULL,
    [Solo]                  DECIMAL (18, 2) NULL,
    [CrossCountry]          DECIMAL (18, 2) NULL,
    [Distance]              DECIMAL (18, 2) NULL,
    [DayTakeoffs]           DECIMAL (18, 2) NULL,
    [DayLandingsFullStop]   DECIMAL (18, 2) NULL,
    [NightTakeoffs]         DECIMAL (18, 2) NULL,
    [NightLandingsFullStop] DECIMAL (18, 2) NULL,
    [AllLandings]           DECIMAL (18, 2) NULL,
    [ActualInstrument]      DECIMAL (18, 2) NULL,
    [SimulatedInstrument]   DECIMAL (18, 2) NULL,
    [HobbsStart]            DECIMAL (18, 2) NULL,
    [HobbsEnd]              DECIMAL (18, 2) NULL,
    [TachStart]             DECIMAL (18, 2) NULL,
    [TachEnd]               DECIMAL (18, 2) NULL,
    [Holds]                 DECIMAL (18, 2) NULL,
    [Approach1]             VARCHAR (100)   NULL,
    [Approach2]             VARCHAR (100)   NULL,
    [Approach3]             VARCHAR (100)   NULL,
    [Approach4]             VARCHAR (100)   NULL,
    [Approach5]             VARCHAR (100)   NULL,
    [Approach6]             VARCHAR (100)   NULL,
    [DualGiven]             DECIMAL (18, 2) NULL,
    [DualReceived]          DECIMAL (18, 2) NULL,
    [SimulatedFlight]       DECIMAL (18, 2) NULL,
    [GroundTraining]        DECIMAL (18, 2) NULL,
    [InstructorName]        VARCHAR (100)   NULL,
    [InstructorComments]    VARCHAR (1000)  NULL,
    [Person1]               VARCHAR (1000)  NULL,
    [Person2]               VARCHAR (1000)  NULL,
    [Person3]               VARCHAR (1000)  NULL,
    [Person4]               VARCHAR (1000)  NULL,
    [Person5]               VARCHAR (1000)  NULL,
    [Person6]               VARCHAR (1000)  NULL,
    [FlightReview]          VARCHAR (100)   NULL,
    [Checkride]             VARCHAR (100)   NULL,
    [IPC]                   VARCHAR (100)   NULL,
    [PilotComments]         VARCHAR (1000)  NULL,
    [PrivatePilotTraining]  VARCHAR (100)   CONSTRAINT [DF_Flights_PrivatePilotTraining] DEFAULT ('FALSE') NULL
);

